-- Belts (grades) and medals: recognition entered by a trainer rather than
-- computed from attendance. One row per grading keeps the history for free;
-- the current grade per section is the highest one. Medals can be linked to
-- an event so tournament results are recorded once, on the event page.

-- ---------------------------------------------------------------------------
-- 1. Grade ladder per section
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.grade_definitions (
    section text NOT NULL,
    grade text NOT NULL,
    "gradeRank" int NOT NULL,
    "beltColor" text NOT NULL,
    "isDan" boolean NOT NULL DEFAULT false,
    CONSTRAINT grade_definitions_pkey PRIMARY KEY (section, grade)
);

INSERT INTO public.grade_definitions (section, grade, "gradeRank", "beltColor", "isDan") VALUES
    -- Judo: coloured kyu belts, black dan belts
    ('Judo', '6. Kyu', 1, '#f5f5f5', false),
    ('Judo', '5. Kyu', 2, '#f4d03f', false),
    ('Judo', '4. Kyu', 3, '#f0932b', false),
    ('Judo', '3. Kyu', 4, '#27ae60', false),
    ('Judo', '2. Kyu', 5, '#2e86de', false),
    ('Judo', '1. Kyu', 6, '#7b4a2d', false),
    ('Judo', '1. Dan', 7, '#111111', true),
    ('Judo', '2. Dan', 8, '#111111', true),
    ('Judo', '3. Dan', 9, '#111111', true),
    ('Judo', '4. Dan', 10, '#111111', true),
    ('Judo', '5. Dan', 11, '#111111', true),
    -- Aikido: white belt through all kyu grades, black from 1. Dan
    ('Aikido', '6. Kyu', 1, '#f5f5f5', false),
    ('Aikido', '5. Kyu', 2, '#f5f5f5', false),
    ('Aikido', '4. Kyu', 3, '#f5f5f5', false),
    ('Aikido', '3. Kyu', 4, '#f5f5f5', false),
    ('Aikido', '2. Kyu', 5, '#f5f5f5', false),
    ('Aikido', '1. Kyu', 6, '#f5f5f5', false),
    ('Aikido', '1. Dan', 7, '#111111', true),
    ('Aikido', '2. Dan', 8, '#111111', true),
    ('Aikido', '3. Dan', 9, '#111111', true),
    ('Aikido', '4. Dan', 10, '#111111', true),
    ('Aikido', '5. Dan', 11, '#111111', true)
ON CONFLICT (section, grade) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 2. Gradings and medals
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.member_grades (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    "memberId" int NOT NULL,
    section text NOT NULL,
    grade text NOT NULL,
    "examDate" text NOT NULL, -- YYYY-MM-DD, like every other date in the app
    note text,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT member_grades_pkey PRIMARY KEY (id),
    CONSTRAINT member_grades_member_fkey FOREIGN KEY ("memberId") REFERENCES public.members(id) ON DELETE CASCADE,
    CONSTRAINT member_grades_grade_fkey FOREIGN KEY (section, grade) REFERENCES public.grade_definitions(section, grade),
    CONSTRAINT member_grades_unique UNIQUE ("memberId", section, grade)
);

CREATE TABLE IF NOT EXISTS public.member_medals (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    "memberId" int NOT NULL,
    "eventId" int,
    competition text NOT NULL,
    date text NOT NULL, -- YYYY-MM-DD
    section text,
    medal text NOT NULL,
    category text, -- e.g. "U18 -66 kg"
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT member_medals_pkey PRIMARY KEY (id),
    CONSTRAINT member_medals_member_fkey FOREIGN KEY ("memberId") REFERENCES public.members(id) ON DELETE CASCADE,
    CONSTRAINT member_medals_event_fkey FOREIGN KEY ("eventId") REFERENCES public.events(id) ON DELETE SET NULL,
    CONSTRAINT member_medals_medal_check CHECK (medal IN ('gold', 'silver', 'bronze')),
    CONSTRAINT member_medals_event_member_unique UNIQUE ("eventId", "memberId")
);

CREATE INDEX IF NOT EXISTS idx_member_grades_member ON public.member_grades("memberId");
CREATE INDEX IF NOT EXISTS idx_member_medals_member ON public.member_medals("memberId");
CREATE INDEX IF NOT EXISTS idx_member_medals_event ON public.member_medals("eventId");

-- RLS
ALTER TABLE public.grade_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.member_grades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.member_medals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated read grade_definitions" ON public.grade_definitions
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow authenticated read member_grades" ON public.member_grades
    FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated insert member_grades" ON public.member_grades
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow authenticated update member_grades" ON public.member_grades
    FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Allow authenticated delete member_grades" ON public.member_grades
    FOR DELETE TO authenticated USING (true);

CREATE POLICY "Allow authenticated read member_medals" ON public.member_medals
    FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated insert member_medals" ON public.member_medals
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow authenticated update member_medals" ON public.member_medals
    FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Allow authenticated delete member_medals" ON public.member_medals
    FOR DELETE TO authenticated USING (true);

-- ---------------------------------------------------------------------------
-- 3. Read functions
-- ---------------------------------------------------------------------------

-- Current (highest) grade per section for one member, with the next grade on the ladder.
CREATE OR REPLACE FUNCTION public.get_member_current_grades(p_member_id int)
RETURNS TABLE (
    section text,
    grade text,
    "gradeRank" int,
    "beltColor" text,
    "isDan" boolean,
    "examDate" text,
    "nextGrade" text
) LANGUAGE sql STABLE SECURITY DEFINER AS $$
    SELECT DISTINCT ON (mg.section)
        mg.section,
        mg.grade,
        gd."gradeRank",
        gd."beltColor",
        gd."isDan",
        mg."examDate",
        (
            SELECT g2.grade FROM public.grade_definitions g2
            WHERE g2.section = mg.section AND g2."gradeRank" = gd."gradeRank" + 1
        ) AS "nextGrade"
    FROM public.member_grades mg
    JOIN public.grade_definitions gd ON gd.section = mg.section AND gd.grade = mg.grade
    WHERE mg."memberId" = p_member_id
    ORDER BY mg.section, gd."gradeRank" DESC, mg."examDate" DESC;
$$;

-- Current grade per member and section, for list views.
CREATE OR REPLACE FUNCTION public.get_members_current_grades()
RETURNS TABLE (
    "memberId" int,
    section text,
    grade text,
    "gradeRank" int,
    "beltColor" text,
    "isDan" boolean
) LANGUAGE sql STABLE SECURITY DEFINER AS $$
    SELECT DISTINCT ON (mg."memberId", mg.section)
        mg."memberId",
        mg.section,
        mg.grade,
        gd."gradeRank",
        gd."beltColor",
        gd."isDan"
    FROM public.member_grades mg
    JOIN public.grade_definitions gd ON gd.section = mg.section AND gd.grade = mg.grade
    ORDER BY mg."memberId", mg.section, gd."gradeRank" DESC, mg."examDate" DESC;
$$;

-- Medal tally per member, for list views.
CREATE OR REPLACE FUNCTION public.get_members_medal_counts()
RETURNS TABLE (
    "memberId" int,
    gold bigint,
    silver bigint,
    bronze bigint
) LANGUAGE sql STABLE SECURITY DEFINER AS $$
    SELECT
        "memberId",
        COUNT(*) FILTER (WHERE medal = 'gold'),
        COUNT(*) FILTER (WHERE medal = 'silver'),
        COUNT(*) FILTER (WHERE medal = 'bronze')
    FROM public.member_medals
    GROUP BY "memberId";
$$;

-- ---------------------------------------------------------------------------
-- 4. Badges earned through grades and medals
-- ---------------------------------------------------------------------------
INSERT INTO public.badge_definitions (id, category, emoji, threshold, "sortOrder", scope) VALUES
    ('black_belt', 'grade', '⚫', NULL, 58, 'lifetime'),
    ('medalist',   'medal', '🎗️', 1,    26, 'lifetime'),
    ('podium_5',   'medal', '🏵️', 5,    44, 'lifetime'),
    ('first_gold', 'medal', '🥇', 1,    46, 'lifetime')
ON CONFLICT (id) DO NOTHING;

-- Award or revoke, so a corrected entry never leaves a stale badge behind.
CREATE OR REPLACE FUNCTION public.refresh_member_grade_medal_badges(p_member_id int)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_has_dan boolean;
    v_medals int;
    v_gold int;
BEGIN
    SELECT EXISTS (
        SELECT 1 FROM public.member_grades mg
        JOIN public.grade_definitions gd ON gd.section = mg.section AND gd.grade = mg.grade
        WHERE mg."memberId" = p_member_id AND gd."isDan"
    ) INTO v_has_dan;

    SELECT COUNT(*)::int, COUNT(*) FILTER (WHERE medal = 'gold')::int
    INTO v_medals, v_gold
    FROM public.member_medals WHERE "memberId" = p_member_id;

    PERFORM public.set_lifetime_badge(p_member_id, 'black_belt', v_has_dan);
    PERFORM public.set_lifetime_badge(p_member_id, 'medalist', v_medals >= 1);
    PERFORM public.set_lifetime_badge(p_member_id, 'podium_5', v_medals >= 5);
    PERFORM public.set_lifetime_badge(p_member_id, 'first_gold', v_gold >= 1);
END;
$$;

CREATE OR REPLACE FUNCTION public.set_lifetime_badge(p_member_id int, p_badge_id text, p_earned boolean)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    IF p_earned THEN
        INSERT INTO public.member_badges ("memberId", "badgeId")
        VALUES (p_member_id, p_badge_id)
        ON CONFLICT DO NOTHING;
    ELSE
        DELETE FROM public.member_badges
        WHERE "memberId" = p_member_id AND "badgeId" = p_badge_id AND season = 0;
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.trigger_refresh_grade_medal_badges()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    IF current_setting('app.skip_badge_refresh', true) = 'true' THEN
        IF TG_OP = 'DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF;
    END IF;

    IF TG_OP IN ('DELETE', 'UPDATE') THEN
        PERFORM public.refresh_member_grade_medal_badges(OLD."memberId");
    END IF;
    IF TG_OP IN ('INSERT', 'UPDATE') THEN
        PERFORM public.refresh_member_grade_medal_badges(NEW."memberId");
    END IF;

    IF TG_OP = 'DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF;
END;
$$;

DROP TRIGGER IF EXISTS trg_badges_on_member_grade ON public.member_grades;
CREATE TRIGGER trg_badges_on_member_grade
    AFTER INSERT OR UPDATE OR DELETE ON public.member_grades
    FOR EACH ROW EXECUTE FUNCTION public.trigger_refresh_grade_medal_badges();

DROP TRIGGER IF EXISTS trg_badges_on_member_medal ON public.member_medals;
CREATE TRIGGER trg_badges_on_member_medal
    AFTER INSERT OR UPDATE OR DELETE ON public.member_medals
    FOR EACH ROW EXECUTE FUNCTION public.trigger_refresh_grade_medal_badges();

-- Full refresh covers grade and medal badges as well.
CREATE OR REPLACE FUNCTION public.refresh_all_member_badges()
RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_member record;
    v_my record;
    v_sy record;
BEGIN
    FOR v_member IN SELECT id FROM public.members LOOP
        PERFORM public.refresh_member_badges(v_member.id);
        PERFORM public.refresh_member_grade_medal_badges(v_member.id);
    END LOOP;

    FOR v_my IN
        SELECT DISTINCT "memberId" AS id, left(date, 4)::int AS y
        FROM public.logs
        WHERE "memberId" IS NOT NULL AND date ~ '^\d{4}-'
    LOOP
        PERFORM public.refresh_member_season_badges(v_my.id, v_my.y);
    END LOOP;

    FOR v_sy IN
        SELECT DISTINCT t.section, left(l.date, 4)::int AS y
        FROM public.logs l
        JOIN public.trainings t ON t.id = l."trainingId"
        WHERE t.section IS NOT NULL AND l.date ~ '^\d{4}-'
    LOOP
        PERFORM public.refresh_section_season_badges(v_sy.section, v_sy.y);
    END LOOP;
END;
$$;
