-- E-mails to trial candidates: a thank-you right after registration, and —
-- after staff previewed them — the waiting-list notice and the training
-- information. The app sends them through the club's SMTP server
-- (src/lib/server/mailer.ts); this migration adds the log and the
-- registration entry point that makes the thank-you possible.
--
--   trial_emails        one row per e-mail: what was sent to whom, when,
--                       and whether it worked. Staff read it; writers log
--                       the mails they send from the dashboard.
--   register_trial()    replaces the public form's direct insert into
--                       members. Validates the input, creates the
--                       candidate and a pending thank-you row, and returns
--                       a one-time token for that row.
--   complete_trial_email()
--                       lets the registration endpoint (running with the
--                       anon key) record the outcome of the thank-you —
--                       only for the row it holds the token of.
--
-- Also records the language the candidate registered in, so mails go out
-- in that language.

ALTER TABLE public.members ADD COLUMN "trialLocale" text;
ALTER TABLE public.members
  ADD CONSTRAINT members_trial_locale_valid
  CHECK ("trialLocale" IS NULL OR "trialLocale" IN ('de', 'en'));

-- ---------------------------------------------------------------------------
-- E-mail log
-- ---------------------------------------------------------------------------

CREATE TABLE public.trial_emails (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id integer NOT NULL REFERENCES public.members (id) ON DELETE CASCADE,
  kind text NOT NULL CHECK (kind IN ('welcome', 'waitlist', 'assigned')),
  to_email text NOT NULL,
  subject text,
  body text,
  -- pending: about to be sent (or the sender died before recording it)
  -- sent / failed: SMTP outcome; skipped: no SMTP server configured
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'sent', 'failed', 'skipped')),
  error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  sent_at timestamptz,
  created_by uuid DEFAULT auth.uid() REFERENCES auth.users (id) ON DELETE SET NULL,
  -- One-time token for complete_trial_email(); cleared once used.
  token uuid
);

CREATE INDEX trial_emails_member_id_idx ON public.trial_emails (member_id, created_at DESC);

ALTER TABLE public.trial_emails ENABLE ROW LEVEL SECURITY;

CREATE POLICY trial_emails_read ON public.trial_emails
  FOR SELECT TO authenticated USING ((SELECT public.is_staff()));

CREATE POLICY trial_emails_insert ON public.trial_emails
  FOR INSERT TO authenticated
  WITH CHECK ((SELECT public.is_writer()) AND status = 'pending' AND token IS NULL);

CREATE POLICY trial_emails_update ON public.trial_emails
  FOR UPDATE TO authenticated
  USING ((SELECT public.is_writer()))
  WITH CHECK ((SELECT public.is_writer()));

REVOKE ALL ON public.trial_emails FROM anon;
GRANT SELECT, INSERT, UPDATE ON public.trial_emails TO authenticated;
GRANT ALL ON public.trial_emails TO service_role;

-- ---------------------------------------------------------------------------
-- Public registration
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.register_trial(
  p_firstname text,
  p_lastname text,
  p_birthday text,
  p_email text,
  p_mobile text DEFAULT NULL,
  p_section text DEFAULT NULL,
  p_notes text DEFAULT NULL,
  p_locale text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_firstname text := nullif(btrim(p_firstname), '');
  v_lastname text := nullif(btrim(p_lastname), '');
  v_email text := nullif(btrim(p_email), '');
  v_birthday text := nullif(btrim(p_birthday), '');
  v_member_id integer;
  v_email_id bigint;
  v_token uuid := gen_random_uuid();
BEGIN
  IF v_firstname IS NULL OR v_lastname IS NULL OR v_email IS NULL OR v_birthday IS NULL THEN
    RAISE EXCEPTION 'firstname, lastname, birthday and email are required'
      USING ERRCODE = '22023';
  END IF;
  IF length(v_firstname) > 100 OR length(v_lastname) > 100 OR length(v_email) > 254
     OR length(coalesce(p_mobile, '')) > 40 OR length(coalesce(p_section, '')) > 60
     OR length(coalesce(p_notes, '')) > 2000 THEN
    RAISE EXCEPTION 'input too long' USING ERRCODE = '22001';
  END IF;
  IF v_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' THEN
    RAISE EXCEPTION 'invalid email' USING ERRCODE = '22023';
  END IF;
  IF v_birthday !~ '^\d{4}-\d{2}-\d{2}$' OR v_birthday::date > current_date THEN
    RAISE EXCEPTION 'invalid birthday' USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.members (
    firstname, lastname, birthday, email, mobile, "trialSection", notes,
    labels, "trialRegisteredAt", "trialLocale"
  ) VALUES (
    v_firstname, v_lastname, v_birthday, v_email,
    nullif(btrim(p_mobile), ''), nullif(btrim(p_section), ''), nullif(btrim(p_notes), ''),
    '["probetraining"]'::jsonb, now(),
    CASE WHEN p_locale IN ('de', 'en') THEN p_locale END
  )
  RETURNING id INTO v_member_id;

  INSERT INTO public.trial_emails (member_id, kind, to_email, token, created_by)
  VALUES (v_member_id, 'welcome', v_email, v_token, NULL)
  RETURNING id INTO v_email_id;

  RETURN jsonb_build_object('emailId', v_email_id, 'token', v_token);
END;
$$;

CREATE OR REPLACE FUNCTION public.complete_trial_email(
  p_id bigint,
  p_token uuid,
  p_status text,
  p_subject text,
  p_body text,
  p_error text DEFAULT NULL
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_status NOT IN ('sent', 'failed', 'skipped') THEN
    RAISE EXCEPTION 'invalid status' USING ERRCODE = '22023';
  END IF;

  UPDATE public.trial_emails
  SET status = p_status,
      subject = left(p_subject, 300),
      body = left(p_body, 10000),
      error = left(p_error, 1000),
      sent_at = CASE WHEN p_status = 'sent' THEN now() END,
      token = NULL
  WHERE id = p_id AND token = p_token AND status = 'pending';

  RETURN FOUND;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.register_trial(text, text, text, text, text, text, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.complete_trial_email(bigint, uuid, text, text, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.register_trial(text, text, text, text, text, text, text, text) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.complete_trial_email(bigint, uuid, text, text, text, text) TO anon, authenticated, service_role;

-- The form now registers through register_trial(); nothing may insert trial
-- candidates into members anonymously any more.
DROP POLICY IF EXISTS members_insert_trial ON public.members;

-- ---------------------------------------------------------------------------
-- Trial overview: expose the registration language (appended column).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW public.view_trial_members
WITH (security_invoker = on) AS
SELECT
    m.id,
    m.firstname,
    m.lastname,
    m.birthday,
    m.email,
    m.mobile,
    m.notes,
    m.labels,
    m."trialSection",
    m."trialRegisteredAt",
    COALESCE(log_count.count, 0)::int AS "attendedCount",
    m."trialStatus",
    m."trialStatusChangedAt",
    m."trialLocale"
FROM public.members AS m
LEFT JOIN (
    SELECT "memberId", COUNT(*) AS count
    FROM public.logs
    GROUP BY "memberId"
) AS log_count ON log_count."memberId" = m.id
WHERE m.labels @> '["probetraining"]'::jsonb;
